language: node_js

node_js: node

notifications:
  email: false

install: npm install

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli

script:
  - gulp lint
  - gulp
  - gulp test
